### ISSUE TITLE
1.12.2 Failed to register dimension for id 53, One is already registered

### ISSUE THREAD

**Issue by KnightBlood** [TheLMiffy1111/EssentialCraft4Unofficial#47] opened 2018-06-12 13:16 UTC
---- Minecraft Crash Report ----

WARNING: coremods are present:
  AstralCore (astralsorcery-1.12.2-1.8.10.jar)
  Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.9.9.1-1.12.2-anarchy.jar)
  llibrary (llibrary-core-1.0.6-1.12.2.jar)
  DCLoadingPlugin (DummyCoreUnofficial-2.4.112.3.jar)
  AppleCore (AppleCore-mc1.12.2-3.1.1.jar)
  CorePlugin (SmoothFont-1.12.2-1.15.jar)
  HammerCoreCore (HammerCore-1.12.2-1.9.9.11.jar)
Contact their authors BEFORE contacting forge

// Daisy, daisy...

Time: 6/12/18 9:12 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from EssentialCraftIVUnofficial (essentialcraft)
Caused by: java.lang.IllegalArgumentException: Failed to register dimension for id 53, One is already registered
	at net.minecraftforge.common.DimensionManager.registerDimension(DimensionManager.java:119)
	at essentialcraft.common.registry.DimensionRegistry.register(DimensionRegistry.java:16)
	at essentialcraft.common.mod.EssentialCraftCore.firstMovement(EssentialCraftCore.java:111)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:627)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:218)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:196)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:627)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:245)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_162, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1104280704 bytes (1053 MB) / 1660944384 bytes (1584 MB) up to 4294967296 bytes (4096 MB)
	JVM Flags: 11 total; -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -Xmn128m -Xmx4096m -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.4.2707 Optifine OptiFine_1.12.2_HD_U_E1_pre 72 mods loaded, 72 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                     | Version                 | Source                                           | Signature                                |
	|:----- |:---------------------- |:----------------------- |:------------------------------------------------ |:---------------------------------------- |
	| UCH   | minecraft              | 1.12.2                  | minecraft.jar                                    | None                                     |
	| UCH   | mcp                    | 9.42                    | minecraft.jar                                    | None                                     |
	| UCH   | FML                    | 8.0.99.99               | forge-1.12.2-14.23.4.2707.jar                    | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | forge                  | 14.23.4.2707            | forge-1.12.2-14.23.4.2707.jar                    | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | smoothfontcore         | 1.12.2-1.14             | minecraft.jar                                    | None                                     |
	| UCH   | foamfixcore            | 7.7.4                   | minecraft.jar                                    | None                                     |
	| UCH   | smoothfont             | 1.12.2-1.15             | SmoothFont-1.12.2-1.15.jar                       | None                                     |
	| UCH   | jei                    | 4.9.1.189               | jei_1.12.2-4.9.1.189.jar                         | None                                     |
	| UCH   | abyssalcraft           | 1.9.4.9                 | AbyssalCraft-1.12.2-1.9.4.9.jar                  | 220f10d3a93b3ff5fbaa7434cc629d863d6751b9 |
	| UCH   | acintegration          | 1.6.2                   | AbyssalCraft+Integration-1.12.2-1.6.2.jar        | 220f10d3a93b3ff5fbaa7434cc629d863d6751b9 |
	| UCH   | orbis_api              | 1.12.2-1.1.4            | orbis_api-1.12.2-1.1.4.jar                       | None                                     |
	| UCH   | aether                 | 1.12.2-1.0.7            | aether_ii-1.12.2-1.0.7.jar                       | None                                     |
	| UCH   | guideapi               | 1.12-2.1.5-60           | Guide-API-1.12-2.1.5-60.jar                      | None                                     |
	| UCH   | bloodmagic             | 1.12.2-2.2.12-97        | BloodMagic-1.12.2-2.2.12-97.jar                  | None                                     |
	| UCH   | animus                 | 1                       | Animus-2.0.1.jar                                 | None                                     |
	| UCH   | applecore              | 3.1.1                   | AppleCore-mc1.12.2-3.1.1.jar                     | None                                     |
	| UCH   | appleskin              | 1.0.9                   | AppleSkin-mc1.12-1.0.9.jar                       | None                                     |
	| UCH   | arcanum                | 1.12.2-4.2.5.1-beta     | arcanum-1.12.2-4.2.5.1-beta.jar                  | None                                     |
	| UCH   | baubles                | 1.5.2                   | Baubles-1.12-1.5.2.jar                           | None                                     |
	| UCH   | astralsorcery          | 1.8.10                  | astralsorcery-1.12.2-1.8.10.jar                  | a0f0b759d895c15ceb3e3bcb5f3c2db7c582edf0 |
	| UCH   | bionisation3           | 1.0.4                   | Bionisation3-1.12.2-1.0.4.jar                    | None                                     |
	| UCH   | bloodarsenal           | 1.12.2-2.1.0-CUSTOM     | BloodArsenal-1.12.2-2.1.0-20.jar                 | None                                     |
	| UCH   | thaumcraft             | 6.1.BETA16              | Thaumcraft-1.12.2-6.1.BETA16.jar                 | None                                     |
	| UCH   | botania                | r1.10-354               | Botania+r1.10-354.jar                            | None                                     |
	| UCH   | codechickenlib         | 3.1.9.344               | CodeChickenLib-1.12.2-3.1.9.344-universal.jar    | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCH   | redstoneflux           | 2.0.2                   | RedstoneFlux-1.12-2.0.2.3-universal.jar          | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCH   | brandonscore           | 2.4.2                   | BrandonsCore-1.12-2.4.2.157-universal.jar        | None                                     |
	| UCH   | cucumber               | 1.1.0                   | cucumber-1.12-1.1.0.jar                          | None                                     |
	| UCH   | cyclopscore            | 0.11.6                  | CyclopsCore-1.12.2-0.11.6.jar                    | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
	| UCH   | draconicevolution      | 2.3.11                  | Draconic-Evolution-1.12-2.3.11.290-universal.jar | None                                     |
	| UCH   | dummycore              | 2.4.112.3.              | DummyCoreUnofficial-2.4.112.3.jar                | None                                     |
	| UCH   | easyretrogen           | 5.0.1                   | EasyRetrogen-1.12.2-5.0.1-universal.jar          | None                                     |
	| UCH   | ebwizardry             | 4.1.2                   | Electroblob's+Wizardry+-+4.1.2+-+MC+1.12.2.jar   | None                                     |
	| UCH   | emberroot              | 1.3.7                   | EmberRootZoo-1.12-1.3.7.jar                      | None                                     |
	| UCH   | embers                 | 0.230                   | embers-0.230.jar                                 | None                                     |
	| UCEE  | essentialcraft         | 4.9.112.3               | EssentialCraftUnofficial-4.9.112.3.jar           | None                                     |
	| UC    | evilcraft              | 0.10.58                 | EvilCraft-1.12.2-0.10.58.jar                     | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
	| UC    | evilcraftcompat        | 1.0.0                   | EvilCraft-1.12.2-0.10.58.jar                     | None                                     |
	| UC    | foamfix                | 0.9.9.1-1.12.2          | foamfix-0.9.9.1-1.12.2-anarchy.jar               | None                                     |
	| UC    | glitchcore             | @MOD_VERSION@           | GlitchCore-1.12.2-1.0.0-universal.jar            | None                                     |
	| UC    | hammercore             | 1.9.9.11                | HammerCore-1.12.2-1.9.9.11.jar                   | 4d7b29cd19124e986da685107d16ce4b49bc0a97 |
	| UC    | harshencastle          | 0.13.1                  | HarshenCastle-0.13.1.jar                         | None                                     |
	| UC    | hexlands               | 1.0.0                   | hexlands-1.1.jar                                 | None                                     |
	| UC    | hungerinpeace          | 1.0.0                   | HungerInPeace-mc1.12-1.0.0.jar                   | None                                     |
	| UC    | waila                  | 1.8.25                  | Hwyla-1.8.25-B40_1.12.jar                        | None                                     |
	| UC    | llibrary               | 1.7.12                  | llibrary-1.7.12-1.12.2.jar                       | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| UC    | iceandfire             | 1.4.0                   | iceandfire-1.4.0-1.12.2.jar                      | None                                     |
	| UC    | mystic                 | 0.7.0                   | Kether-1.12-1.12.2-0.7.jar                       | None                                     |
	| UC    | mysticalagriculture    | 1.6.11                  | mysticalagriculture-1.12-1.6.11.jar              | None                                     |
	| UC    | mysticalagradditions   | 1.2.8                   | mysticalagradditions-1.12-1.2.8.jar              | None                                     |
	| UC    | nei                    | 2.4.1                   | NotEnoughItems-1.12.2-2.4.1.233-universal.jar    | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UC    | oreexcavation          | 1.4.119                 | OreExcavation-1.4.119.jar                        | None                                     |
	| UC    | harvestcraft           | 1.12.2u                 | Pam's+HarvestCraft+1.12.2u.jar                   | None                                     |
	| UC    | roots                  | 0.104                   | roots-2-0.104.jar                                | None                                     |
	| UC    | soot                   | 0.18hotfix              | Soot-0.18hotfix.jar                              | None                                     |
	| UC    | soulshardstow          | 1.12-2.7.6-56           | SoulShards-TOW-1.12-2.7.6-56.jar                 | None                                     |
	| UC    | soulshardsrespawn      | 1.12.2-1.0.5-7          | SoulShardsRespawn-1.12.2-1.0.5-7.jar             | None                                     |
	| UC    | spiceoflife            | 1.3.11                  | SpiceOfLife-mc1.12-1.3.11.jar                    | None                                     |
	| UC    | thaumadditions         | 2r                      | ThaumicAdditions-1.12.2-2r.jar                   | 4d7b29cd19124e986da685107d16ce4b49bc0a97 |
	| UC    | thaumicbases           | 3.0.085.30b             | thaumicbases-3.0.105.30b.jar                     | None                                     |
	| UC    | tcinventoryscan        | 2.0.10                  | ThaumicInventoryScanning_1.12.2-2.0.10.jar       | None                                     |
	| UC    | thaumicperiphery       | 0.2.3                   | thaumicperiphery-0.2.3.jar                       | None                                     |
	| UC    | toughasnails           | 3.1.0.119               | ToughAsNails-1.12.2-3.1.0.119-universal.jar      | None                                     |
	| UC    | twilightforest         | 3.7.424                 | twilightforest-1.12.2-3.7.424-universal.jar      | None                                     |
	| UC    | vampirism              | 1.4.2                   | Vampirism-1.12.2-1.4.2.jar                       | None                                     |
	| UC    | teamlapen-lib          | 1.4.2                   | Vampirism-1.12.2-1.4.2.jar                       | None                                     |
	| UC    | vampirism_integrations | vampirism_integrations  | VampirismIntegrations-1.12.2-1.0.0.jar           | None                                     |
	| UC    | veinminer              | 0.38.2                  | VeinMiner-1.12-0.38.2.647+b31535a.jar            | None                                     |
	| UC    | veinminermodsupport    | 0.38.2                  | VeinMiner-1.12-0.38.2.647+b31535a.jar            | None                                     |
	| UC    | wailaharvestability    | 1.1.12                  | WailaHarvestability-mc1.12-1.1.12.jar            | None                                     |
	| UC    | wawla                  | 2.5.256                 | Wawla-1.12.2-2.5.256.jar                         | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UC    | hungeroverhaul         | 1.12.2-1.3.3.jenkins148 | HungerOverhaul-1.12.2-1.3.3.jenkins148.jar       | None                                     |

	Loaded coremods (and transformers): 
AstralCore (astralsorcery-1.12.2-1.8.10.jar)
  
Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.9.9.1-1.12.2-anarchy.jar)
  pl.asie.foamfix.coremod.FoamFixTransformer
llibrary (llibrary-core-1.0.6-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
DCLoadingPlugin (DummyCoreUnofficial-2.4.112.3.jar)
  DummyCore.ASM.DCASMManager
AppleCore (AppleCore-mc1.12.2-3.1.1.jar)
  squeek.applecore.asm.TransformerModuleHandler
CorePlugin (SmoothFont-1.12.2-1.15.jar)
  bre.smoothfont.asm.Transformer
HammerCoreCore (HammerCore-1.12.2-1.9.9.11.jar)
  com.pengu.hammercore.asm.HammerCoreTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 391.35' Renderer: 'GeForce GTX 850M/PCIe/SSE2'
	Hammer Core Information: FluidDictionary Info: Registered 2 fluids.
OreDictionary Info: Registered 171 names; 201 stacks.
Pastebin Connection: Okay.
	[DummyCore]: 'Special case ASM modification mods: ''Note, that these mods might not be involved in the crash in ANY WAY!''DummyCore just prints some known mods for a lot of ASM modifications''dummycore''CodeChickenLib'
	OptiFine Version: OptiFine_1.12.2_HD_U_E1_pre
	OptiFine Build: 20180516-180318
	Render Distance Chunks: 8
	Mipmaps: 0
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 391.35
	OpenGlRenderer: GeForce GTX 850M/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 4

**Comment by TheLMiffy1111** [comment] 2018-06-12 14:21
Duplicate of #25

**Closed as completed by TheLMiffy1111** 2018-06-12 14:21 UTC
